-- CreateTable
CREATE TABLE "footer_settings" (
    "id" TEXT NOT NULL,
    "footerContent" TEXT,
    "copyright" TEXT,
    "disclaimer" TEXT,
    "aboutTagline" TEXT,
    "quickLinks" JSONB,
    "showSocialMedia" BOOLEAN NOT NULL DEFAULT true,
    "facebookUrl" TEXT,
    "instagramUrl" TEXT,
    "linkedinUrl" TEXT,
    "youtubeUrl" TEXT,
    "twitterUrl" TEXT,
    "whatsappUrl" TEXT,
    "customSocialIcon" TEXT,
    "customSocialUrl" TEXT,
    "showLogo" BOOLEAN NOT NULL DEFAULT true,
    "logoUrl" TEXT,
    "showLanguageSelector" BOOLEAN NOT NULL DEFAULT false,
    "supportedLanguages" TEXT[],
    "showNewsletter" BOOLEAN NOT NULL DEFAULT false,
    "newsletterPlaceholder" TEXT,
    "mailServiceConfig" JSONB,
    "backgroundColor" TEXT DEFAULT '#1A1A1A',
    "textColor" TEXT DEFAULT '#E9E7E2',
    "columnLayout" INTEGER NOT NULL DEFAULT 3,
    "customCSS" TEXT,
    "showLegalLinks" BOOLEAN NOT NULL DEFAULT true,
    "privacyPolicyUrl" TEXT,
    "termsConditionsUrl" TEXT,
    "cookiePolicyUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "footer_settings_pkey" PRIMARY KEY ("id")
);
